language: python

services:
  - docker

before_script:
- touch .env_server
- echo PYTHONUNBUFFERED=$PYTHONUNBUFFERED >> .env_server
- echo DEBUG=$DEBUG >> .env_server
- echo PORT=$PORT >> .env_server
- echo HOST=$HOST >> .env_server
- echo FLASK_ENV=$FLASK_ENV >> .env_server
- echo FLASK_APP=$FLASK_APP >> .env_server
- echo SECRET_KEY=$SECRET_KEY >> .env_server
- echo DATABASE=$DATABASE >> .env_server
- echo MONGO_USERNAME=$MONGO_USERNAME >> .env_server
- echo MONGO_PASSWORD=$MONGO_PASSWORD >> .env_server
- echo MONGO_DATABASE=$MONGO_DATABASE >> .env_server
- echo MONGO_HOST=$MONGO_HOST >> .env_server
- echo MONGO_PORT=$MONGO_PORT >> .env_server
- echo CODECOV_TOKEN=$CODECOV_TOKEN >> .env_server
- CI_ENV=`bash <(curl -s https://codecov.io/env)`
- CI_ENV=(${CI_ENV//-e/})
- for i in \"${CI_ENV[@]}\"; do echo $i= >> .env_server; done
- touch .env_database
- echo MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE >> .env_database
- echo MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME >> .env_database
- echo MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD >> .env_database

script:
- export 
- make test
