version: '3'
services:
  server:
    container_name: pladmed-server
    image: server:latest
    entrypoint: ./docker-entrypoint.sh
    command: python3 main.py #python3 pladmed/main.py #flask run --host 0.0.0.0
    env_file:
      - .env_server
    volumes:
      - ./pladmed:/home/pladmed
      - ./logs:/home/logs
      - ./mongo/mongod.conf:/etc/mongod.conf
    ports:
      - 5000:5000
    restart: on-failure
    networks:
      - pladmed_net

  db:
    image: 'mongo:3.6'
    container_name: pladmed-database
    env_file:
      - .env_database
    volumes:
      - ./mongodb:/data/db
    restart: on-failure
    networks:
      - pladmed_net

  chrony:
    cap_add:
      - 'SYS_TIME'
    image: chrony
    container_name: chrony
    networks:
      - pladmed_net

networks:
  pladmed_net:
